### PR TITLE
Txnquery multi response handling

### PR DESCRIPTION
**Pull request by israelshirk**
Enables the response parser to handle txnquery responses.  Work by @jrzerr and based on #3.  All changes on top of that PR are encapsulated in 1db0a20.  Please let me know if you have any questions or need tweaks.  Thanks!  Israel

### CODE REVIEW

**Comment by markroland** [comment]
Thanks for the updates! I think it's kind of confusing to have methods so similar in name ("sendRequest" and "_sendRequest"). Can we leave "sendRequest" alone and rename your "_sendRequest" to "sendMultiRequest"?

**Comment by israelshirk** [comment]
@jrzerr ^^^

**Comment by markroland** [comment]
Hey guys, I didn't realize @jrzerr branch was based off of  @israelshirk's so when I just committed his PR from months ago it committed this as well. I may go ahead and make my proposed change. I don't think it should matter since they are private methods.

**Comment by markroland** [comment]
I just made my updates on this. Please let me know if this causes any issues for you. Thanks for your input on this project.

**Comment by israelshirk** [comment]
No worries, LGTM.  I think we mixed up branches internally - we'll just pull yours in.  Thanks!

**Pull request merged**
